<?php $td = 'anyipsum'; ?>
<style>
	.anyipsum-help p {
		margin-bottom: 2em;
	}
	ul {
		margin-top: 0;
	}
</style>

<div class="anyipsum-help">

	<h3 class="title"><?php _e('Shortcode', $td); ?></h3>
	<p>
		<?php _e('Add a form to any page or post to generate your custom ipsum', $td); ?>: <strong>[anyipsum-form]</strong>
	</p>

	<h3 class="title"><?php _e('API Parameters', $td); ?></h3>
	<p>
		<ul>
			<li><strong>type</strong>: <strong>all-custom</strong> for custom only or <strong>custom-and-filler</strong> for custom mixed with miscellaneous filler.</li>
			<li><strong>paras</strong>: <em>optional</em> number of paragraphs, defaults to 5.</li>
			<li><strong>sentences:</strong> number of sentences (this overrides paragraphs)</li>
			<li><strong>start-with-lorem</strong>: <em>optional</em> pass <strong>1</strong> to start the first paragraph with your custom Starts With text (ex: 'Bacon ipsum dolor sit amet').</li>
		</ul>
	</p>

	<h3 class="title"><?php _e('Filters', $td); ?></h3>
		<ul>
			<li>
				<strong>anyipsum-generate-filler</strong>: // TODO
			</li>
			<li>
				<strong>anyipsum-form</strong>: <?php _e('Customize the HTML form generated by the anyipsum-form shortcode') ?>
			</li>
			<li>
				<strong>anyipsum-form-output</strong>: <?php _e('Customize the generated custom ipsum created by the anyipsum-form shortcode') ?>
			</li>
		</ul>
	<p>
	</p>

	<h3 class="title"><?php _e('Contact', $td); ?></h3>
	<p>
		<?php _e('E-Mail', $td) ?>: <a href="mailto:pete@petenelson.com">pete@petenelson.com</a><br/>
		<?php _e('Twitter', $td) ?>: <a href="https://twitter.com/GunGeekATX" target="_blank">@GunGeekATX</a><br/>
		<?php _e('GitHub', $td) ?>: <a href="https://github.com/petenelson/wp-any-ipsum" target="_blank">https://github.com/petenelson/wp-any-ipsum</a><br/>
	</p>

</div>