<?php
if ( ! defined( 'ABSPATH' ) ) die( 'restricted access' );
?>
<style>
	.anyipsum-help p {
		margin-bottom: 2em;
	}
	.anyipsum-help .indent {
		text-indent: 2em;
	}
	ul {
		margin-top: 0;
	}
</style>

<div class="anyipsum-help">

	<h3 class="title"><?php esc_html_e( 'Shortcode', 'any-ipsum' ); ?></h3>
	<p>
		<?php esc_html_e( 'Add a form to any page or post to generate your custom ipsum', 'any-ipsum' ); ?>: <strong>[anyipsum-form]</strong><br/>
		<?php esc_html_e( 'You can also add a header that\'s displayed at the beginning of the form and is hidden when the form is submitted' ) ?>: <strong>[anyipsum-form]<?php esc_html_e( 'Give our ipsum generator a try!  It\'s the best!', 'any-ipsum' ); ?>[/anyipsum-form]</strong>
	</p>

	<h3 class="title"><?php esc_html_e( 'API Parameters', 'any-ipsum' ); ?></h3>
	<p>
		<ul>
			<li><strong>type</strong>: <strong><?php echo esc_attr( apply_filters( 'anyipsum-setting-get', '', 'anyipsum-settings-general', 'querystring-all-custom' ) ); ?></strong> for custom only or <strong><?php echo esc_attr( apply_filters( 'anyipsum-setting-get', '', 'anyipsum-settings-general', 'querystring-all-custom' ) ); ?></strong> <?php esc_html_e( 'for custom mixed with miscellaneous filler.', 'any-ipsum' ); ?></li>
			<li><strong>paras</strong>: <em><?php esc_html_e( 'optional', 'any-ipsum' ) ?></em> <?php esc_html_e( 'number of paragraphs, defaults to 5.', 'any-ipsum' ); ?></li>
			<li><strong>sentences:</strong> <?php esc_html_e( 'number of sentences (this overrides paragraphs)', 'any-ipsum' ); ?></li>
			<li><strong>start-with-lorem</strong>: <em><?php esc_html_e( 'optional', 'any-ipsum' ) ?></em> <?php esc_html_e( 'pass <strong>1</strong> to start the first paragraph with your custom Start With text', 'any-ipsum' ) ?> ('<?php echo esc_attr( apply_filters( 'anyipsum-setting-get', '', 'anyipsum-settings-general', 'start-with' ) );  ?>').</li>
		</ul>
	</p>

	<h3 class="title"><?php esc_html_e( 'Filters', 'any-ipsum' ); ?></h3>
		<ul>
			<li>
				<strong>anyipsum-generate-filler</strong>: <?php esc_html_e( 'Returns an array of paragraphs', 'any-ipsum' ); ?>, <?php esc_html_e( 'Parameters', 'any-ipsum' ); ?>:
				<ul>
					<li class="indent">$args: <?php esc_html_e( 'array containing the same parameters as above (type, paras, etc)', 'any-ipsum' ); ?></li>
				</ul>
			</li>
			<li>
				<strong>anyipsum-form</strong>: <?php esc_html_e( 'Customize the HTML form generated by the anyipsum-form shortcode' ) ?>, <?php esc_html_e( 'Parameters', 'any-ipsum' ); ?>:
				<ul>
					<li class="indent">$form: <?php esc_html_e( 'Default HTML form' ); ?></li>
				</ul>
			</li>
			<li>
				<strong>anyipsum-form-output</strong>: <?php esc_html_e( 'Customize the generated custom ipsum created by the anyipsum-form shortcode', 'any-ipsum' ); ?>, <?php esc_html_e( 'Parameters', 'any-ipsum' ); ?>:
				<ul>
					<li class="indent">$output: <?php esc_html_e( 'Default output', 'any-ipsum' ); ?></li>
					<li class="indent">$paragraphs: <?php esc_html_e( 'Paragraphs of generated ipsum', 'any-ipsum' ); ?></li>
				</ul>
			</li>
		</ul>
	<p>
	</p>

	<h3 class="title"><?php esc_html_e( 'Contact', 'any-ipsum' ); ?></h3>
	<p>
		<?php esc_html_e( 'E-Mail', 'any-ipsum' ) ?>: <a href="mailto:pete@petenelson.com">pete@petenelson.com</a><br/>
		<?php esc_html_e( 'Twitter', 'any-ipsum' ) ?>: <a href="https://twitter.com/CodeGeekATX" target="_blank">@CodeGeekATX</a><br/>
		<?php esc_html_e( 'GitHub', 'any-ipsum' ) ?>: <a href="https://github.com/petenelson/wp-any-ipsum" target="_blank">https://github.com/petenelson/wp-any-ipsum</a><br/>
	</p>

</div>
